baseURL: "https://docs.stefanopulze.com/"
languageCode: "en-US"
title: 'Stefano Pulze'
theme: 'journal-22'

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    style: monokai
    lineNos: false
    noClasses: false
