baseURL: "https://docs.stefanopulze.com/"
languageCode: "en-US"
title: 'Stefano Pulze'
theme: 'journal-22'
# theme: 'hugo-theme-novela'
googleAnalytics: 'G-GZEH8CJ8G0'

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    style: monokai
    lineNos: false
    noClasses: false

enableRobotsTXT: true
disableKinds:
  - taxonomy
  - term
  - categories
  - rss
  - sitemap