name: backend-ci

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Submodules
        shell: bash
        run: |
          git submodule init
          git submodule update

      - name: Test
        shell: bash
        run: |
          pwd
          ls
          ls themes/journal-22/static/icons

      - name: Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: stefanopulze/ftp-sync@v1.0
        with:
          server: "${{secrets.FTP_SERVER}}"
          username: "${{secrets.FTP_USERNAME}}"
          password: "${{ secrets.FTP_PASSWORD }}"
          localDir: 'public/'
          remoteDir: '.'
